//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtask
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public string text { get; set; }
        public bool isFinish { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
