//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Subtask = new HashSet<Subtask>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
        public bool isFinish { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Subtask> Subtask { get; set; }
    }
}
